site_url: https://templatecookie-nuxt.netlify.app/
logo_url: https://templatecookie-nuxt.netlify.app/logo.png
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - { label: Site Description, name: sitedescription, widget: string, hint: 'This is used as descriptive text for links that link to this site', }
  - name: "product" # Used in routes, e.g., /admin/collections/blog
    label: "Product" # Used in the UI
    folder: "content/products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "product" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Product Category", name: "product_category", widget: "relation", collection: "category", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - name: "gallery"
        label: "Gallery"
        folder: "images/gallery" # The path to the folder where the documents are stored
        widget: "list"
        optional: true
        create: true # Allow users to create new documents in this collection
        fields:
          - { label: "Title", name: "imgTitle", widget: "string", required: false }
          - { label: "Description", name: "imgDesc", widget: "string", required: false }
          - { label: "Gallery Image", name: "imgSrc", widget: "image" }
      - { label: "Demo Link", name: "link", widget: "string", required: false }
      - { label: "Download Link", name: "download", widget: "string", required: false }
      - { label: "Purchase Link", name: "purchase", widget: "string", required: false }
      - { label: "Version", name: "version", widget: "string" }
      - { label: "Product Price", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Template Feature", name: "template_feature", widget: "markdown" }
  - name: "category" # Used in routes, e.g., /admin/collections/blog
    label: "Category" # Used in the UI
    folder: "content/categories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "category" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "banner", widget: "image", required: false }
      - { label: "Seo Description (max-158 character)", name: "description", widget: "markdown", required: false }
local_backend: true
